name: scipp-docs

channels:
  - conda-forge

# Note that since the scipp package is installed after this environment is created (and Conda is a pain) this list must include the dependencies of the Scipp package also.
# This is essentially everything in the "run" section of conda/meta.yml.
dependencies:
  - appdirs
  - doxygen
  - ipython=7.2.0
  - pip
  - pandoc
  - python>=3
  - python-configuration
  - pyyaml
  - sphinx>=1.6
  - sphinx_rtd_theme
  - tbb
  - numpy
  - pip:
    - ipyevents
    - ipyvolume
    - ipywidgets
    - matplotlib
    - nbsphinx
